# Site settings
title: Agehua-Blog
email: "lijixin88@gmail.com"
description: "人不逍遥名逍遥"
baseurl: ""
url: "http://agehua.github.io"
permalink: /:year/:title


# Social account
# twitter:  PeiwenLu
weibo:    jixinli
github:   agehua
# codepen:  P233
# dribbble: username


# Comment
disqus_shortname: agehua


# Google Analytics
google_analytics: UA-39647668-2


# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed
gems:
  - jekyll-sitemap


safe: false
cdn_url : http://7xuos6.com2.z0.glb.qiniucdn.com/

JB :
  ASSET_PATH : false
  IMAGE_PATH : false
