# highlighter: pygments
# markdown: redcarpet
# redcarpet:
#   extensions:
#     - fenced_code_blocks
#     - no_intra_emphasis
#     - strikethrough
#     - autolink
#     - tables

# 作者信息
author:
  name: Damon Chen
  email: zhenchentl@gmail.com
  link: http://zhenchen.me
  weibo: http://weibo.com/markchentl
  github: http://github.com/zhenchentl

# 站点信息
title: Damon Chen的博客
description: Damon Chen的博客
url: http://zhenchen.me
language: 中文
