permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

#highlighter: rouge

kramdown:
  input: GFM

# 作者信息
author:
  name: Mark Chen
  email: zhenchentl@gmail.com
  link: http://zhenchen.me
  weibo: http://weibo.com/markchentl
  github: http://github.com/zhenchentl

# 站点信息
title: Mark Chen的博客
description: Mark Chen的博客
url: http://zhenchen.me
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://mc-tuchuang.qiniudn.com/mygavatar
favicon: http://mc-tuchuang.qiniudn.com/favicon.png

# baidu analytics 设置
analytics:
  provider: custom

# disqus 设置
disqus:
  shortname: markchen

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates:
#  - Python
#  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
